### ISSUE TITLE
Cant run yarn:admin 

### ISSUE THREAD

**Issue by pradeepdigispice** [ever-co/ever#1004]
ERROR in error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.
../node_modules/@angular-devkit/core/src/terminal/caps.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/engine/engine.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/engine/interface.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/sink/dryrun.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/sink/host.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/sink/sink.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/tree/action.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/tree/delegate.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/tree/host-tree.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/tree/interface.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@angular-devkit/schematics/src/utility/update-buffer.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
../node_modules/@types/stripe/index.d.ts:39:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

39 /// <reference types="node" />
                         ~~~~
../node_modules/subscriptions-transport-ws/dist/server.d.ts:1:23 - error TS4090: Conflicting definitions for 'node' found at '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@types/node/ts3.2/index.d.ts' and '/Users/harish/Downloads/ever-develop/admin/website-angular/node_modules/@wry/context/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

1 /// <reference types="node" />
                        ~~~~
app/@core/data/admins.service.ts:78:33 - error TS2339: Property 'updateAdmin' does not exist on type '{ id: string; updateInput: IAdminUpdateObject; }'.

78  			map((result) => result.data.updateAdmin),
    			                            ~~~~~~~~~~~
app/@core/data/device.service.ts:115:46 - error TS2339: Property 'update' does not exist on type 'IDeviceRawObject'.

115  			map((result) => result.data.updateDevice.update),
     			                                         ~~~~~~
app/@core/data/device.service.ts:134:33 - error TS2339: Property 'removeDeviceByIds' does not exist on type '{}'.

134  			map((result) => result.data.removeDeviceByIds),
     			                            ~~~~~~~~~~~~~~~~~
app/@core/data/device.service.ts:140:3 - error TS2322: Type 'Observable<IDeviceRawObject>' is not assignable to type 'Observable<Device>'.
  Type 'IDeviceRawObject' is missing the following properties from type 'Device': isDeleted, CreateObjectTYPE, RawObjectTYPE, createdAt, and 3 more.

140  	return this.apollo
     	~~~~~~~~~~~~~~~~~~
141  		.mutate<{ createDevice: IDeviceRawObject }>({
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
155  			share()
    ~~~~~~~~~~~
156  		);
    ~~~~~
app/@core/data/invites-requests.service.ts:119:33 - error TS2339: Property 'createInviteRequest' does not exist on type '{ createInput: IInviteRequestCreateObject; }'.

119  			map((result) => result.data.createInviteRequest),
     			                            ~~~~~~~~~~~~~~~~~~~
app/@core/data/invites-requests.service.ts:137:33 - error TS2339: Property 'removeInvitesRequestsByIds' does not exist on type '{}'.

137  			map((result) => result.data.removeInvitesRequestsByIds),
     			                            ~~~~~~~~~~~~~~~~~~~~~~~~~~
app/@core/data/invites-requests.service.ts:167:33 - error TS2339: Property 'updateInviteRequest' does not exist on type '{ id: string; updateInput: IInviteRequestUpdateObject; }'.

167  			map((result) => result.data.updateInviteRequest),
     			                            ~~~~~~~~~~~~~~~~~~~
app/@core/data/invites.service.ts:104:33 - error TS2339: Property 'createInvite' does not exist on type '{ createInput: IInviteCreateObject; }'.

104  			map((result) => result.data.createInvite),
     			                            ~~~~~~~~~~~~
app/@core/data/invites.service.ts:122:33 - error TS2339: Property 'removeInvitesByIds' does not exist on type '{}'.

122  			map((result) => result.data.removeInvitesByIds),
     			                            ~~~~~~~~~~~~~~~~~~
app/@core/data/invites.service.ts:149:33 - error TS2339: Property 'updateInvite' does not exist on type '{ id: string; updateInput: IInviteUpdateObject; }'.

149  			map((result) => result.data.updateInvite),
     			                            ~~~~~~~~~~~~
app/@core/data/products.service.ts:101:33 - error TS2339: Property 'createProduct' does not exist on type '{ product: IProductCreateObject; }'.

101  			map((result) => result.data.createProduct),
     			                            ~~~~~~~~~~~~~
app/@core/data/products.service.ts:121:33 - error TS2339: Property 'saveProduct' does not exist on type '{ product: Product; }'.

121  			map((result) => result.data.saveProduct),
     			                            ~~~~~~~~~~~
app/@core/data/products.service.ts:139:33 - error TS2339: Property 'removeProductsByIds' does not exist on type '{}'.

139  			map((result) => result.data.removeProductsByIds),
     			                            ~~~~~~~~~~~~~~~~~~~
app/@core/data/productsCategory.service.ts:66:33 - error TS2339: Property 'createProductsCategory' does not exist on type '{ productsCategory: IProductsCategoryCreateObject; }'.

66  			map((result) => result.data.createProductsCategory),
    			                            ~~~~~~~~~~~~~~~~~~~~~~
app/@core/data/productsCategory.service.ts:105:33 - error TS2339: Property 'updateProductsCategory' does not exist on type '{ id: string; productsCategory: IProductsCategoryCreateObject; }'.

105  			map((result) => result.data.updateProductsCategory),
     			                            ~~~~~~~~~~~~~~~~~~~~~~
app/@core/data/warehouseOrders.service.ts:39:33 - error TS2339: Property 'createOrder' does not exist on type '{}'.

39  		.map((result) => result.data.createOrder);
    		                             ~~~~~~~~~~~
app/@core/data/warehouses.service.ts:220:33 - error TS2339: Property 'warehouseAddProducts' does not exist on type '{ warehouseId: string; products: IWarehouseProduct[]; }'.

220  			map((result) => result.data.warehouseAddProducts),

**Comment by evereq** [comment]
@pradeepdigispice can you try with Node v10, please? You may need to kill your node_modules folder and `yarn install` again...
