### ISSUE TITLE
Bug: multiple deletion does not work - it only deletes one of the selected

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1009]
In the admin module, when deleting multiple merchants
Or in the admin module, when deleting multiple carriers

![](https://user-images.githubusercontent.com/59708947/75585969-12f3b100-5a52-11ea-8bc1-1c6c71596251.png)

![](https://user-images.githubusercontent.com/59708947/75586057-45051300-5a52-11ea-901f-2c1be88e4def.png)

**Comment by AlishMekliov931** [comment]
@morggansoft  The bug is fixed, you can pull latest changes from develop branch and test again.

**Comment by morggansoft** [comment]
Thanks. Verified. Closing the issue.
