### ISSUE TITLE
Admin: Customers -> Management labels translations issues

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1010]
When clicking on devices al labels become code

![image](https://user-images.githubusercontent.com/59708947/75587513-6287ac00-5a55-11ea-9e8c-2b9148bc3c5f.png)

![image](https://user-images.githubusercontent.com/59708947/75587553-77643f80-5a55-11ea-9348-545ea0d4af20.png)

**Comment by morggansoft** [comment]
same for product categories

![image](https://user-images.githubusercontent.com/59708947/75588117-bb0b7900-5a56-11ea-9cc3-d3741db4b8f0.png)

![image](https://user-images.githubusercontent.com/59708947/75588164-d37b9380-5a56-11ea-9aaf-f7a300e6a12c.png)

**Comment by AlishMekliov931** [comment]
@morggansoft the bug is fixed, you can pull changes from the develop branch and test.

**Comment by morggansoft** [comment]
Thanks @AlishMekliov931, we will be verifying.

**Comment by morggansoft** [comment]
Thanks. Verified and working correctly.

**Comment by morggansoft** [comment]
Detected something that didn't go right.

When selecting product categories:

![image](https://user-images.githubusercontent.com/59708947/76043421-4e045180-5f36-11ea-8caa-e4a5aee77115.png)

Language switches alone to English, while setting still being on Spanish:

![image](https://user-images.githubusercontent.com/59708947/76043493-7b50ff80-5f36-11ea-8080-2b657c4883ec.png)
