### ISSUE TITLE
Feature: default Location should be used when creating store or carrier

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1016]
this is the .env file:

![image](https://user-images.githubusercontent.com/59708947/75781227-960b5480-5d3b-11ea-8f49-fc1a398d0b87.png)

But when creating a store:

![image](https://user-images.githubusercontent.com/59708947/75781421-e2ef2b00-5d3b-11ea-8dde-e94bfb40e867.png)

Or a carrier:

![image](https://user-images.githubusercontent.com/59708947/75781522-1d58c800-5d3c-11ea-965b-01227c93b81d.png)

And when creating the delivery zones, too.

It defaults to 0º latitude, 0º longitude, the intersections of the Greenwich meridian with the equator

---
We checked the environment.ts and it is correctly generated with the correct latitude configured in the .env. Though it is not taken into account.

I suspect it could be related to issues #978 and #1014

**Comment by evereq** [comment]
@AlishMekliov931 basically, when default location set in the .env file, we should set automatically location of store and carrier close to that default location. That's useful for testing of everything (not really needed for the production of course)

**Comment by morggansoft** [comment]
Got you @evereq ! So is there any current use for the default location in the Admin module? I thought that if there was any, that would be it. That's why I thought it was something that was not working instead of not implemented...

**Comment by AlishMekliov931** [comment]
The changes are pushed in develop branch, you can pull and test.

**Comment by morggansoft** [comment]
Thanks. Verified and working correctly. Closing issue.
