### ISSUE TITLE
Mobile Shop: Some user texts cannot be changed through the language files.

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1020]
Will put some examples:

In mobile shop, stores:

![image](https://user-images.githubusercontent.com/59708947/75980917-296e9200-5ec2-11ea-816b-dda44692409c.png)

**Comment by YavorGrancharov** [comment]
Finished!

**Comment by YavorGrancharov** [comment]
Finished!
![78553460-f3e6fc80-7811-11ea-9c98-eed6e858af37](https://user-images.githubusercontent.com/28997304/78808215-cb0b6680-79cd-11ea-87ce-7d10a57f5ac4.gif)
