### ISSUE TITLE
Carrier: Default Location on Carrier whitout DEFAULT_LATITUDE DEFAULT_LONGITUD

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1026]
We remove DEFAULT_LATITUDE DEFAULT_LONGITUD from .env file to use real user location, but location when the carrier is login the Location is on Bulgaria, it´s any default location setting hardcode?

**Comment by AlishMekliov931** [comment]
@morggansoft If you are removed completely the settings for default location the app will use own default ones which are hard coded by code (same for rest apps which use default location). So if you wanna the app to not use any default location, you need to have such settings in .env file but without values, example:
```
DEFAULT_LATITUDE=
DEFAULT_LONGITUDE=
```

**Comment by AlishMekliov931** [comment]
@morggansoft did you test with `DEFAULT_LATITUDE=
DEFAULT_LONGITUDE=`. Can we close this issue?

**Comment by morggansoft** [comment]
Sure. Thanks
