### ISSUE TITLE
Admin : Manage Store : Use specific carriers checkbox is not working

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1029]
Start checking store configuration:

![image](https://user-images.githubusercontent.com/59708947/76563333-f447de00-6485-11ea-8fbd-d5f9ea322473.png)

Buying in mobile shop

![image](https://user-images.githubusercontent.com/59708947/76563416-20635f00-6486-11ea-8e60-17511f455971.png)

orders appears in merchant:

![image](https://user-images.githubusercontent.com/59708947/76563476-3e30c400-6486-11ea-9aac-3522709e4832.png)

Advance order

![image](https://user-images.githubusercontent.com/59708947/76563546-66202780-6486-11ea-9bfc-1fdc9b66445d.png)

loging in carrier Lucas Gonzalez

![image](https://user-images.githubusercontent.com/59708947/76563591-7c2de800-6486-11ea-8ac6-7cfdff0861f9.png)

![image](https://user-images.githubusercontent.com/59708947/76563633-8cde5e00-6486-11ea-8a7a-a83cb62161f0.png)

Ok so far.

Logging in with another carrier Juan Pitaluga (in another browser (incognito window)):

![image](https://user-images.githubusercontent.com/59708947/76563772-d62ead80-6486-11ea-8ff2-6ce2762a94af.png)

![image](https://user-images.githubusercontent.com/59708947/76563821-e8105080-6486-11ea-87d5-23061ea41238.png)

Oops, juan pitaluga should not be able to take this work because of the store settings.

**Comment by AlishMekliov931** [comment]
@morggansoft We added an additional settings which will clarify the delivery, i.e Use All Carriers  mean that can be used all carriers no matter of selected (currently only this work). And will implement a feature for the rest types - Use only store carriers and Prefer store carriers, see a little demo: https://www.screencast.com/t/VH7PsqSo.

cc: @evereq

**Comment by AlishMekliov931** [comment]
@evereq If we have created feature task for the rest type of delivery "Use Only Store Carriers" and "Prefer Store Carriers" we can close this issue.

**Comment by evereq** [comment]
@AlishMekliov931 did you created such tasks? Because I think I don't :D I'll close this ticket anyway for now...
