### ISSUE TITLE
Carrier: When an order is handed to a carrier, if customer cancels, the carrier still sees the trip

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1030]
From the shop module I made a purchase and from the merchant app I advanced it until it is waiting for a carrier to pick it up

In the carrier up, appears the work and to take work or not.

In the meanwhile I cancel the order from the mobile shop.

It is canceled everywhere except from the carrier, the carrier still being able to see the trip.

**Comment by evereq** [comment]
See demo https://www.screencast.com/t/K4yRtAD5YF
