### ISSUE TITLE
Admin: Translation Label on Store Managment page

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1032]
On Admin module, there is one label without translation on Store Management, maybe it's hardcode: label is "Payment".
![admin_bug2_1](https://user-images.githubusercontent.com/59708947/76647143-f7e96c80-653a-11ea-99a6-1fb678b7b50a.png)

**Comment by YavorGrancharov** [comment]
Finished!
![78559026-547b3700-781c-11ea-9a06-880882c2028f](https://user-images.githubusercontent.com/28997304/78807917-66500c00-79cd-11ea-8aea-0ea435ec5911.gif)
