### ISSUE TITLE
Admin: Show on Map Button 

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1038]
When clicking on Show on Map button on Stores list, the map is loading on Bulgaria, but the Stores are on Uruguay. The default location to visualize this information maybe can set on .env file.

![show on map button 1](https://user-images.githubusercontent.com/59708947/77334039-0e45b400-6d03-11ea-9580-d60ff902c96f.png)

![show on map button 2](https://user-images.githubusercontent.com/59708947/77334051-1140a480-6d03-11ea-829a-768333aab619.png)

**Comment by AlishMekliov931** [comment]
The problem is fixed, now the center will be based on default location settings in .env file
```
DEFAULT_LATITUDE,
DEFAULT_LONGITUDE
```
