### ISSUE TITLE
Admin: Show on Map Option

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1039]
Translations of labels on Show on Map screen is not correct. May be there can load from .json file.

![show on map button 2](https://user-images.githubusercontent.com/59708947/77334432-8ad89280-6d03-11ea-974c-8f2da2053237.png)

_Translations

**Comment by YavorGrancharov** [comment]
Finished!

**Comment by YavorGrancharov** [comment]
Finished by Tsvetelina Yordanova!
