### ISSUE TITLE
Admin:  there are columns on Lists that are not showing well

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1042]
On Admin module, there are lists that do not show the content of the last column.
There are:
Stores list, Products list, Customers list, Carriers list.

![list 1](https://user-images.githubusercontent.com/59708947/77337055-27506400-6d07-11ea-848b-0cd2185bda98.png)
![list 2](https://user-images.githubusercontent.com/59708947/77337067-2b7c8180-6d07-11ea-9aee-5bbfa9c2f33a.png)
![list 3](https://user-images.githubusercontent.com/59708947/77337081-2e777200-6d07-11ea-997f-75342a2dc064.png)
![list 4](https://user-images.githubusercontent.com/59708947/77337089-31726280-6d07-11ea-9ce4-8a73fb8a8ceb.png)

**Comment by evereq** [comment]
@morggansoft hm, on your screenshot you have settings panel open which of course rendered above the table. Normally, if you close that panel (click on "settings" icon in the header), all table columns should be visible again :)
