### ISSUE TITLE
Admin: Store Product List 

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1043]
On Store product list, when edit one product, the Edit page is load well, but when try to back to Store product list clicking on back arrow on left up corner, the Admin module return to Products Management list.

![products 1](https://user-images.githubusercontent.com/59708947/77347617-e1030100-6d16-11ea-92bf-371d57426738.png)
![products 2](https://user-images.githubusercontent.com/59708947/77347648-ebbd9600-6d16-11ea-86be-5b87dc353352.png)
![products 3](https://user-images.githubusercontent.com/59708947/77347661-efe9b380-6d16-11ea-811d-33b24e0a173d.png)

**Comment by morggansoft** [comment]
appears same as #979

**Comment by YavorGrancharov** [comment]
Finished!
![78634682-2560d600-78ad-11ea-93a6-2947a5f201bd](https://user-images.githubusercontent.com/28997304/78807518-dd38d500-79cc-11ea-879d-563ded6ed4ff.gif)
