### ISSUE TITLE
Merchant: Popup Informational

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1046]
On Merchant, when the user finishes creating a new order the popup appears.

![quitar popup de desarrollo](https://user-images.githubusercontent.com/59708947/77974043-64e75b00-72cc-11ea-80ae-bbafc0ab6b2b.png)

**Comment by evereq** [comment]
@AlishMekliov931 we need more context for when such notification appears on the screen. Is it when customer confirms a new order or? Of course, we need to make such notification to look better, but we need first to understand why it appears :)

**Comment by AlishMekliov931** [comment]
@evereq This popup is shown when the merchant create order for some User, and notify that the order is created. https://www.loom.com/share/b5f7ecb1223445babae5e096f66995c3

Note that we have same functionality on Admin app https://www.loom.com/share/1b61dd3a3da646169c3a39342e0c697d

**Comment by evereq** [comment]
@morggansoft we removed that popup, it was not needed and used just for debugging :)
