### ISSUE TITLE
Merchant: New Client Translation

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1047]
On Merchant, When create a new Client the suggest Address is not .json translation

![Traduccion al crear cliente en Merchant](https://user-images.githubusercontent.com/59708947/77974158-b09a0480-72cc-11ea-8b34-c438ffe489db.png)

**Comment by YavorGrancharov** [comment]
Done!
![EqTGq9cXCv](https://user-images.githubusercontent.com/28997304/80096679-9d4c2300-8572-11ea-95f3-700a6175e7c0.gif)
