### ISSUE TITLE
Merchant: No client data

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1048]
On Merchant, when creating a new order, the Client list is empty, but on Admin, there are many Clients associated with the restaurant.

On Merchant Client list:
![Clientes existen pero no se muestran en Merchant 2](https://user-images.githubusercontent.com/59708947/77974336-2dc57980-72cd-11ea-968e-3428d5e25ba0.png)

On Admin Client list:
![Clientes existen pero no se muestran en Merchant 1](https://user-images.githubusercontent.com/59708947/77974360-42097680-72cd-11ea-8100-c2816817383f.png)

**Comment by sunk0** [comment]
![JOcMGt2BZO](https://user-images.githubusercontent.com/36041324/86001073-10f92900-ba17-11ea-9104-ca7c64a10f4e.gif)

@morggansoft I don't see a problem here can you show me video how you get to the problem?

**Comment by morggansoft** [comment]
We continue without load customers list. 
Show on video:

https://www.loom.com/share/bdc4fdea6fb34b2abb39a3267ec554bd

**Comment by morggansoft** [comment]
This is the throwing error:

ERROR TypeError: Cannot read property 'id' of null
    at 19.9c28c5b03dffb8847edf.js:1
    at Array.map (<anonymous>)
    at t._formatDataSmartTable (19.9c28c5b03dffb8847edf.js:1)
    at e._next (19.9c28c5b03dffb8847edf.js:1)
    at e.__tryOrUnsub (main.f40070c73ec7a7b07107.js:1)
    at e.next (main.f40070c73ec7a7b07107.js:1)
    at e._next (main.f40070c73ec7a7b07107.js:1)
    at e.next (main.f40070c73ec7a7b07107.js:1)
    at e._next (main.f40070c73ec7a7b07107.js:1)
    at e.next (main.f40070c73ec7a7b07107.js:1)

**Comment by sunk0** [comment]
![oGLMMGSrMA](https://user-images.githubusercontent.com/36041324/86512704-0bcc1d80-be0d-11ea-9641-f9c05ab2d7d9.gif)

**Comment by sunk0** [comment]
Strange that i don't have the same problem @morggansoft

**Comment by morggansoft** [comment]
Ok, we don't get ir working in our instance. How do you want to proceed to troubleshoot?

**Comment by evereq** [comment]
@valiopld please try to reproduce this on your PC :)

**Comment by valiopld** [comment]
@evereq 
There is no error message and everyhing work expected on my PC
https://www.loom.com/share/f50532ed146d461da86ddb193279478e

**Comment by evereq** [comment]
@morggansoft seems 2 our devs separately say it works :) So maybe you need to merge the latest code to your code base and recreate DB (reseed) to make it work, not sure :)
