### ISSUE TITLE
Carrier: Incomplete Order

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1049]
On Carrier, when the carriers take an order with many products to deliver, only one product is showing on the screen, but the total price is about all products present on the original order.

Creating new order with many products:
![no muestra pedido completo en carrier 1](https://user-images.githubusercontent.com/59708947/77974618-0d49ef00-72ce-11ea-8771-e64932b67ed8.png)

On Merchant is showing all products Ok:
![no muestra pedido completo en carrier 2](https://user-images.githubusercontent.com/59708947/77974644-20f55580-72ce-11ea-88d4-305c4c8e215c.png)

On Carrier not showing all products in the order to deliver:
![no muestra pedido completo en carrier 3](https://user-images.githubusercontent.com/59708947/77974666-37031600-72ce-11ea-9718-55b7e84b1b30.png)

The total price it`s OK:
![no muestra pedido completo en carrier 4](https://user-images.githubusercontent.com/59708947/77974695-4d10d680-72ce-11ea-85ca-29e1004243a5.png)

On Admin, the order it´s store complete on the database:
![no muestra pedido completo en carrier 5](https://user-images.githubusercontent.com/59708947/77974730-631e9700-72ce-11ea-842c-6a3f3f71ef0b.png)

**Comment by evereq** [comment]
@morggansoft it seems to be implemented now, at least we can see it in https://github.com/ever-co/ever/pull/1167 screenshots
