### ISSUE TITLE
Merchant: Close panel to add new customer 

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1050]
When creating a new order from the Merchant Dashboard, on Add Customer option, the close panel button not working.

![Merchant boton cerrar nuevo cliente no funciona](https://user-images.githubusercontent.com/59708947/78198262-6e083180-745e-11ea-9f93-918c92b666b3.png)

**Comment by YavorGrancharov** [comment]
I took another approach which was to hide the closing button as we already have routes on warehouse page form which user can shoose. Another problem was that the used mutation component is a modal and when we are on customers page and try to create new customer the modal and the coresponding close button works fine. When we are on warehouse page trying to create customer the closing button doesn't corespong with the same mutation component.
![ONiN3nRLCc](https://user-images.githubusercontent.com/28997304/80571255-f6013d00-8a04-11ea-9df4-a8ce40c345e8.gif)
