### ISSUE TITLE
Merchant: Error Popup on New Order panel not have a json language file translation

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1051]
When try to create a new order on Merchant Dashboard with empty Customer, an error is showing on popup, but not have a json language file translation associated.

![Merchant mensaje sin traduccion](https://user-images.githubusercontent.com/59708947/78198483-16b69100-745f-11ea-8ded-3fa1ed7b9c5c.png)

**Comment by YavorGrancharov** [comment]
Done!
![W9lkVbaZO2](https://user-images.githubusercontent.com/28997304/80227059-d3ae9e80-8655-11ea-8b1a-4ee1de79354d.gif)

**Comment by evereq** [comment]
@YavorGrancharov same question I asked already in Pull Request you made... On Video we see that lots of tabs / elements does not have any text, does it fixed now? E.g. when you click on Tabs, how do you know what you click? It's clearly a bug, is it fixed???
