### ISSUE TITLE
Merchant: track order is not assigned json language file translations

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1052]
On Merchant, when a user watches a history order, the tracking window functionality does not have JSON language file translations associated. 

![Merchant En el seguimiento de la orden falta asignar traducciones](https://user-images.githubusercontent.com/59708947/78198628-8462bd00-745f-11ea-9907-03e334f48c10.png)

**Comment by YavorGrancharov** [comment]
Done!
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/28997304/80341180-9d963800-886a-11ea-89d2-e9ec6b05a418.gif)
