### ISSUE TITLE
Merchant: new product functionality error on translations

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1053]
On Merchant Dashboard, the new product functionality does not have JSON language file translations on some labels.

![Merchant al editar un producto no estan asignadas traducciones](https://user-images.githubusercontent.com/59708947/78198748-f935f700-745f-11ea-8bc5-f1ca33a5449d.png)

**Comment by YavorGrancharov** [comment]
Already working!

![ezgif com-optimize](https://user-images.githubusercontent.com/28997304/80094606-3711d100-856f-11ea-9e69-5dfcbea45d18.gif)
