### ISSUE TITLE
Unable to run on Win 10 / unable to build on Centos / demo links broken

### ISSUE THREAD

**Issue by dhagan** [ever-co/ever#1057]
Unable to run on Win 10 / unable to build on Centos 7/ demo links broken

I
$ yarn run:server
yarn run v1.22.4
$ yarn --cwd ./backend/api start
$ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn tsc
&& node build/main.js
\backend\api\node_modules\.bin\tsc
src/graphql/geo-locations/merchants/geo-location-merchants.resolver.ts:5:19 - err
or TS2307: Cannot find module '@modules/server.common/utils'.

I tried running the symlink commands

cmd /c rmdir .\admin\website-angular\src\modules\server.common
The directory name is invalid.  

and 

C:\_dhagan\try\ever>mklink /D admin\website-angular\src\modules\server.common shared\core
Cannot create a file when that file already exists.

-------------------

I have tried multiple times on two different Windows 10 boxes.

git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git
git config --global core.symlinks true
git config --global submodule.recurse true
yarn bootstrap
yarn run:server

-----
On vBox/Centos

[ever]$ node --version
v12.16.1
[ever]$ npm --version
6.13.4
[ever]$ yarn -versiopn
1.22.4

-- Failed to execute '/usr/local/n/versions/node/12.16.1/bin/node /home/vagrant/_dhagan/ever/backend/api/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/vagrant/_dhagan/ever/backend/api/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/vagrant/_dhagan/ever/backend/api/node_modules/bcrypt/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'ever-api'

**Comment by evereq** [comment]
@dhagan we pushed significant improvements in the architecture into the `develop` branch. Now, you don't need to use symlinks etc, and installation/setup should be much more simple and straightforward. So you can clone repo again and try to setup it. See updated README file for more details, it's basically just a few commands which should make it all working. 

We also updated Demo links in README, thank you for notification. 
I am closing this ticket, but feel free to report if you still have issues.

**Comment by dhagan** [comment]
Demo links load, but accounts and passwords don't exist.  Thank you for the reply, will test build and report back.
