### ISSUE TITLE
Bug: docker-compose build fails

### ISSUE THREAD

**Issue by tamal-appsbee** [ever-co/ever#1074]
![image](https://user-images.githubusercontent.com/8500385/79628766-92078a80-8161-11ea-8915-d108b990603e.png)

docker-compose up 
giving failed response.

**Comment by evereq** [comment]
@tamal-appsbee thank you for reporting, we did not update yet Docker / Docker-compose for the new structure of modules. @suryasingh working on it and we will let you know when it fixed.

**Comment by tamal-appsbee** [comment]
ok, Thanks

**Comment by evereq** [comment]
@tamal-appsbee we recently did lots of improvements / fixing for docker / docker-compose, it's already in `develop` branch, will appreciate getting your feedback!

**Comment by tamal-appsbee** [comment]
Thank you guys.
