### ISSUE TITLE
Bug: admin site translation issues while traversing menu

### ISSUE THREAD

**Issue by dhagan** [ever-co/ever#1075]
Clicking around shows HEADER_VIEW.EVER®HEADER_VIEW.ADMIN and cannot get the styling to reload.    Uploaded a 8 second video to discord channel

**Comment by evereq** [comment]
Video https://www.screencast.com/t/40wfivNswP

**Comment by AlishMekliov931** [comment]
@evereq In this video you can see that the problem is fixed, so we can close this issue.
https://www.loom.com/share/c184b3f3632a4ac58b518e433fe9665e
