### ISSUE TITLE
Angular crashes on both admin and web

### ISSUE THREAD

**Issue by sirramin** [ever-co/ever#1092]
When running server, admin and shopweb on branch develop angular crashed and variables has shown.

![Untitled](https://user-images.githubusercontent.com/3243902/81505435-56955180-9304-11ea-8cbd-d631697c2d65.png)

![Untitled2](https://user-images.githubusercontent.com/3243902/81505437-585f1500-9304-11ea-8206-7a075efee847.jpg)

**Comment by evereq** [comment]
Hi @sirramin can you give us more info about your environment? OS, Node version, Yarn version?

**Comment by sirramin** [comment]
I tried on Windows 10 and Ubuntu.
Node: 10.15.3 And 12.16.1
Yarn: 1.22.4

**Comment by YavorGrancharov** [comment]
Fixed on PR #1128 !
