### ISSUE TITLE
could not find a copy of typescript node_modules -- help?

### ISSUE THREAD

**Issue by luisfranciscocesar** [ever-co/ever#1095]
yarn bootstrap

error An unexpected error occurred: "could not find a copy of typescript to link in /home/luis/documents/ever/node_modules/rxjs-tslint/node_modules"

**Comment by evereq** [comment]
@luisfranciscocesar hm, we never saw this before I think, needs to know more about your env:
- OS
- NodeJs version
- Yarn version
- rxjs-tslint version (in `/home/luis/documents/ever/node_modules/rxjs-tslint` folder)

**Comment by luisfranciscocesar** [comment]
when I remove the yarn.lock file, which comes in ever. I get that error. shouldn't because yarn.lock is on gigitnore

**Comment by luisfranciscocesar** [comment]
I discovered that when I delete the yarn.lock that comes in ever I get that error, but if so why is the yarn.lock in gigitnore ?.

**Comment by evereq** [comment]
@luisfranciscocesar sorry we can't explain that error, but I removed now yarn.lock from .gitignore, it should be committed to repo actually, thank you!
