### ISSUE TITLE
Feature: ability to disable password change for Admin user and disable fake data generator

### ISSUE THREAD

**Issue by evereq** [ever-co/ever#1097]
We need to add 2 optional settings to API Backend (in .env):

1) ADMIN_PASSWORD_RESET - if set to false, should NOT allow change of Admin user password

2) FAKE_DATA_GENERATOR - if set to false, Admin UI should NOT display a menu item for Fake Data Generation and if we have relevant APIs, we need to make sure such APIs disabled too. 

The idea that on demo/production server, for example, it's best to not allow changing of Super Admin password and also disable fake data generator too.

**Comment by AlishMekliov931** [comment]
Default values if such settings not exist in .ent file will be "false", because improper use of them can provide issues
ADMIN_PASSWORD_RESET = false
FAKE_DATA_GENERATOR = false

**Comment by evereq** [comment]
@AlishMekliov931 I think we now need to update our Demo server with this (latest code from `develop` branch) and make sure this features are disabled on it (after we generate fake data)
