### ISSUE TITLE
Merchant New customer countries list

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1139]
When creating new customers from Merchant countries list isn't in alphabetic order. Some countries mixed not in order appear.

![Captura de Pantalla 2020-06-24 a la(s) 23 09 45](https://user-images.githubusercontent.com/59708947/85646057-a1c7b180-b671-11ea-9ee7-51a37898dca0.png)

**Comment by tsvetelina-e-y** [comment]
this is same as #1137
