### ISSUE TITLE
Merchant New customer error 

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1140]
When creating new customer, save button trowing an error on console, and not save data on the database

![Captura de Pantalla 2020-06-24 a la(s) 23 24 46](https://user-images.githubusercontent.com/59708947/85646251-1a2e7280-b672-11ea-9f7c-d5d473b25ecd.png)

**Comment by YavorGrancharov** [comment]
Didn't reproduced the described error! 
https://www.loom.com/share/ffb8bbd13b0d43b984e581c6a521cf44

**Comment by morggansoft** [comment]
This error It´s on Merchant App, not in Admin.

**Comment by YavorGrancharov** [comment]
Provided video preview is from Merchant app!

**Comment by morggansoft** [comment]
Hi Yavor, here the [link](https://www.loom.com/share/206721f88a0e40628fab2480cafbd439)

Throw an error when finding customers when creating new customers. All examples are on video.

**Comment by YavorGrancharov** [comment]
Hi, it is fixed! I didn't get the error at first as I was creating customer from customers page and not from orders page like on a second video you provided.
https://www.loom.com/share/7e3899cde6cd4b31af68336ec786be41
