### ISSUE TITLE
Merchant tracking order

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1141]
On Merchant tracking order not have translations

![Captura de Pantalla 2020-06-24 a la(s) 23 32 12](https://user-images.githubusercontent.com/59708947/85646707-0cc5b800-b673-11ea-92e4-d3cb0972cce0.png)

**Comment by YavorGrancharov** [comment]
Didn't reproduce the described error!
https://www.loom.com/share/ec10d318035f4043bc92d046e63b5924

**Comment by evereq** [comment]
@morggansoft closing it as seems translation works well now
