### ISSUE TITLE
Merchant customer list

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1142]
When select Customer list on Merchant not showing any data and throwing error on console

![Captura de Pantalla 2020-06-24 a la(s) 23 36 51](https://user-images.githubusercontent.com/59708947/85646972-be64e900-b673-11ea-9a49-78561417857e.png)

**Comment by valiopld** [comment]
I dont have this issue @evereq 
https://www.loom.com/share/0364d3e1f72344638f4b611450d6a533

**Comment by evereq** [comment]
@morggansoft closing for now as seems it works
