### ISSUE TITLE
Merchant carriers list

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1143]
On Merchant when there are carriers working on deliveries, carrier list not showing anything

![Captura de Pantalla 2020-06-24 a la(s) 23 41 18](https://user-images.githubusercontent.com/59708947/85647428-d38e4780-b674-11ea-984a-584e32117773.png)

![Captura de Pantalla 2020-06-24 a la(s) 23 41 32](https://user-images.githubusercontent.com/59708947/85647441-d7ba6500-b674-11ea-9148-5531c1b63be9.png)

![Captura de Pantalla 2020-06-24 a la(s) 23 41 39](https://user-images.githubusercontent.com/59708947/85647413-ccffd000-b674-11ea-9cda-39650ddf4aeb.png)

**Comment by sunk0** [comment]
@morggansoft you need to add carriers from top right corner

**Comment by morggansoft** [comment]
Can you show what you mean?

**Comment by sunk0** [comment]
https://www.loom.com/share/f47a017f3e7a466590565598a7734a1a @morggansoft
