### ISSUE TITLE
Merchant not listing Customers

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1157]
On Merchant App when try to list customers not showing anything and throw an error. 
Path is http://test.tupedido.uy:4202/customers

![Captura de Pantalla 2020-06-28 a la(s) 21 04 12](https://user-images.githubusercontent.com/59708947/85961781-26bd0e80-b983-11ea-82fc-16440ae1dc0e.png)

**Comment by YavorGrancharov** [comment]
I think that in this section we show only customers that made at least one order from the shop as can be seen on video below!
Didn't reproduced the error from the provided screenshot!
https://www.loom.com/share/fe0cc5aaa93b4b34b0dd80944d713791

**Comment by morggansoft** [comment]
Hi @YavorGrancharov I show on video this error. There are customers with more than one order finished associated with the store, but not load this customers list on Merchant.
Show this on video:

https://www.loom.com/share/13cd67d1bccf46e688032beaef40b963

**Comment by YavorGrancharov** [comment]
Still cant reproduce this issue!
https://www.loom.com/share/c3c2d7ef7c3d46e2bee99b96f41d374e

**Comment by morggansoft** [comment]
Hi Yavor, Perhaps it is an error in our database, Ruslan suggested us to install the system again in a new instance, which we already have installed, but we did not test it again. We can close this bug, and if it is repeated in the new instance we will recreate it. Thus it does not appear as open, Do you agree?

**Comment by YavorGrancharov** [comment]
Of course, no problem,if it appeared again then I will try to figure it out
what may cause the issue!

На пн, 10.08.2020 г., 18:38 ч. morggansoft <notifications@github.com>
написа:

**Comment by morggansoft** [comment]
Closed because it could not be reproduced, it could be an error in the data of the DB
