### ISSUE TITLE
Admin Module not allow Save button

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1171]
When Edit Store data, and I try to change some value, the Save button is disabled. 

![Captura de Pantalla 2020-06-30 a la(s) 15 04 02](https://user-images.githubusercontent.com/59708947/86161260-5e42cc80-bae3-11ea-9a48-913cb81d19ad.png)

**Comment by YavorGrancharov** [comment]
Duplicate with #1153  !

**Comment by morggansoft** [comment]
Sorry, I close this.
