### ISSUE TITLE
New pick up order error

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1188]
When creating a New Order from MobileShop on Pick Up modality, it appears correctly in Merchant Dashboard, and on MobileShop interface show correct information about there. But when the new order is finished on Merchant, there appears on Carrier´s App to delivery, and this is an error because the order is picked up by the customer.

Show cycle on Video:

https://www.loom.com/share/cebb8f17d17f4722b15bb0de1542e578

**Comment by evereq** [comment]
@valiopld assigning to you to double-check this
