### ISSUE TITLE
Admin Module error on edit Customer data

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#1190]
When edit Customer address data there change on the database but not refresh textbox value.
Show there on video:

https://www.loom.com/share/31e2dd6818674e1b9d5263759754db9d

**Comment by YavorGrancharov** [comment]
Everything seems to work as it should! Provided a video below.
https://www.loom.com/share/a4dfe94f5d5d4caa9a0e2f4ee1912924

**Comment by evereq** [comment]
@morggansoft probably fixed already, closing for now
