### ISSUE TITLE
webshop / orders - store data is not updating immediately

### ISSUE THREAD

**Issue by valiopld** [ever-co/ever#1206]
https://www.loom.com/share/e1ff5ac023c046fdbe9dee59a9d2b411

In webshop/ orders - when subscribing to the store the received data is not immediately displaying 
Sometimes it takes a few seconds, sometimes you need to click somewhere and then changes happen 
In the video, you can figure it when you look at the store logo

**Comment by valiopld** [comment]
via Hubstaff
User: Valentin Peshev

Project: Ever Platform - https://app.hubstaff.com/projects/1101750
Date Range: 07/07/20 - 07/07/20
Work session total: 0:44:43
Billable: No

Grand total: 0:44:43

**Comment by evereq** [comment]
@morggansoft closing as seems it's fixed now after the PR merged.
