### ISSUE TITLE
In Merchant app Scan aint working

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1226]
https://www.loom.com/share/c2f5070712eb47b5aee0431d22e8b0ac

**Comment by BlagovestGerov** [comment]
@sunk0  Cordova plugins are not available when running the app in the browser with ionic serve. In order to be able to use the Cordova plugins, you'd need to run the app on a simulator / real device.

**Comment by sunk0** [comment]
@BlagovestGerov good to know can i somehow test it if it works?

**Comment by BlagovestGerov** [comment]
Yes, you could use the Android Studio Emulator https://developer.android.com/studio/run/emulator.
