### ISSUE TITLE
On Mobile Shop scan ain't working

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1231]
https://www.loom.com/share/e3b0c5d5d7044bbfbdba6dfa7d48adaf

**Comment by BlagovestGerov** [comment]
The same here. Cordova plugins are not available when running the app in the browser with ionic serve. In order to be able to use the Cordova plugins, you'd need to run the app on a simulator / real device.

You could use the Android Studio Emulator https://developer.android.com/studio/run/emulator
