### ISSUE TITLE
On Admin panel when updating store to Inactive not showing products

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1242]
https://www.loom.com/share/36edb777f7644587b0e0b8b256feefa3

**Comment by evereq** [comment]
@YavorGrancharov see https://github.com/ever-co/ever/issues/1244#issuecomment-660871811

**Comment by YavorGrancharov** [comment]
Fixed
https://www.loom.com/share/3e22677a8e004fd2aa6223365aa40847
