### ISSUE TITLE
Product availability in Mobile Web app problem

### ISSUE THREAD

**Issue by sunk0** [ever-co/ever#1250]
https://www.loom.com/share/a7253480067e4d0c872362ec0c7b96b0

Two variants are here:

1-st Make the card that shows the product on top left corner available/not available and set flag on the buy button
2-nd Make the card not visible at all

**Comment by YavorGrancharov** [comment]
Already fixed in PR https://github.com/ever-co/ever/pull/1258
https://www.loom.com/share/a88713ed0eea4c678e7d45435faa52f8
