### ISSUE TITLE
Bug: Fake data generator may fail because of non working fake image URLs

### ISSUE THREAD

**Issue by evereq** [ever-co/ever#1295]
From customer report:

> When I try creating fake data in ever admin using below I am seeing this error in console log and after that script stops running and also product list is empty in shop web screen

![image](https://user-images.githubusercontent.com/118497/89148809-7f279300-d563-11ea-8469-8e868f1bb67b.png)

![image](https://user-images.githubusercontent.com/118497/89148787-746cfe00-d563-11ea-9070-52a66d6b0d36.png)

> I was able to figure out the issue probably, these 3 images are returning 404. If we remove images it works fine 
> https://images.pexels.com/photos/629093/pexels-photo-629093.jpeg?auto=compress&cs=tinysrgb&h=350
> https://images.pexels.com/photos/1268549/pexels-photo-1268549.jpeg?auto=compress&cs=tinysrgb&h=350
> https://images.pexels.com/photos/1246957/pexels-photo-1246957.jpeg?auto=compress&cs=tinysrgb&h=350

**Comment by evereq** [comment]
@YavorGrancharov I am thinking maybe sometimes during fake data generator work, fake images got generated wrong way and did not load and that cause somehow the whole process of seed stop? Please check how fake product pictures are generated, maybe we need to add there some kind of "try/catch" block, so some products might be generated without images but it did not broke the whole seed process.

**Comment by YavorGrancharov** [comment]
Fixed
https://www.loom.com/share/c7fff8f0376b464886b129ad7f1e72f0
