### ISSUE TITLE
The server responds with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ZinnerRep** [ever-co/ever#438]
I am running the server, the database and the admin website, when I try to generate initial data in the Setup page in the admin website I get repeating error:
GET http://localhost:5500/socket.io/?EIO=3&transport=poll

**Comment by evereq** [comment]
@ZinnerRep which branch did you try `master` or `develop`? 
Also can you please attach screenshots from server console and from Chrome Dev tools in the browser (the way that we see both the page URL and requests that failing).

One of our developers will try to reproduce it now with a "clean" setup and will let you know.

**Comment by evereq** [comment]
@ZinnerRep thanks to your bug report our developer @AlishMekliov931 was able to identify a bug and solve it (at least we hope so): https://github.com/ever-co/ever/commit/9c5c15f4881fd2abcf43800bc3cd628dd380ea61.

Please try to pull the latest from the `develop` branch and it should be working now!

**Comment by ZinnerRep** [comment]
@evereq I cloned using: `git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git`, the branch is master and I followed the standard installation.
Chrome incognito mode:
![issue-tag438](https://user-images.githubusercontent.com/40530313/56377052-5c079180-6201-11e9-873b-75fe11bf1cbf.png)

VS Code + admin and api terminals:
![issue-tag438-vscode](https://user-images.githubusercontent.com/40530313/56377107-88231280-6201-11e9-843d-380f3efb569d.png)

Thanks for the respond.

**Comment by evereq** [comment]
@ZinnerRep we pushed fix only to branch `develop`, so you suppose to clone with 
`git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git --branch develop`, not master...

In any case, I will also push it now to `master`, so others don't get into the same issue, thank you!

**Comment by ZinnerRep** [comment]
I fixed it by modifying the code in 9c5c15f. Thanks.
