### ISSUE TITLE
Cannot find module '@modules/server.common/enums/OrderWarehouseStatus'.

### ISSUE THREAD

**Issue by SaddamDeveloper** [ever-co/ever#519]
please help me to solve that issue??

**Comment by evereq** [comment]
Hi @SaddamDeveloper it looks like you have issues with "symlinks".
Did you enable symlinks like described here https://github.com/ever-co/ever/blob/develop/README.md#clone-repo?
Please read all relevant section in Readme, I think it is an issue with how you cloned repo, maybe you need to run command prompt as administrator if you on Windows (or use 'sudo' on Linux)

If above did not help, we will need screenshots of how you cloned and run project.

**Comment by evereq** [comment]
@SaddamDeveloper did you figure out the issue? If not, please feel free to contact us via some chat so we can help you with setup, see https://github.com/ever-co/ever#contact-us

**Comment by SaddamDeveloper** [comment]
Definitely. I will get back to you.

**Comment by SaddamDeveloper** [comment]
![5](https://user-images.githubusercontent.com/36893768/59741485-bf0cb780-9288-11e9-8dfe-10bc1151cf7d.JPG)

Still same problem sir.
Here is the step How I clone this.
In Administrator mode
1. git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git
2. cd ever 
3. git config --global core.symlinks true
git config --global submodule.recurse true
(I am using git version 2.19.1.windows.1)

4. npm install -g yarn@latest
5. yarn bootstrap
6. after succefull the package extraction an installation of all I am trying to start the server by "yarn run:server"
7. but it shows something like the screenshot

**Comment by evereq** [comment]
@SaddamDeveloper what output you get when running this command: `node -v`?

Also, could you please copy/past here all output from `git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git`, I think something wrong with permissions and you are getting some errors during cloning process... (you should try to run that command as an administrator on Windows)

**Comment by SaddamDeveloper** [comment]
node -v 
v10.15.3

**Comment by SaddamDeveloper** [comment]
![6](https://user-images.githubusercontent.com/36893768/59746078-b5d51800-9293-11e9-8d38-ceeff530f131.JPG)

**Comment by SaddamDeveloper** [comment]
Sir any update???

**Comment by evereq** [comment]
@SaddamDeveloper so far we can't reproduce that issue... Tried on multiple PCs with Windows 10, everywhere all going fine for us... It looks like you are having some issues with symlinks, but we just can't reproduce it... What Windows version do you use? After you clone repo, what do you see if you try to browse folder like `admin\website-angular\src\modules\server.common`? Do you see files? Because that folder should be a symlink to `shared\core` folder

**Comment by SaddamDeveloper** [comment]
![ds](https://user-images.githubusercontent.com/36893768/60756469-22357280-a01b-11e9-9989-41f4058b52a5.JPG)
Folder looks like this screenshot. Yes files are available. I am using Windows 10 Education 64 bit.

**Comment by evereq** [comment]
@SaddamDeveloper I am sorry, but I have no exact answers for you... i.e. from errors in your screenshot, it's clear that your TypeScript transpiler can't locate files in the `backend\api\src\modules\server.common` folder. However, you see the same files in your Explorer... So it must be something with TypeScript permission to follow symlinks, but we never saw anything like that before... We are working currently to replace symlinks to shared modules with npm packages, but it will be available only in a few months. Till that, I believe you can only try to figure out permissions issues for TypeScript or to setup project on some other PC or using Virtual PC / Virtual Box (e.g. on Ubuntu Linux running inside a virtual machine on your PC).

**Comment by SaddamDeveloper** [comment]
Finally successfully done sir.

**Comment by healer2030** [comment]
> Finally successfully done sir.

May I know what you did? 
I have the same issue

**Comment by evereq** [comment]
@healer2030 , I am not sure what @SaddamDeveloper did exactly, but if you get similar issues you can try to just copy manually folder `shared/core` content into `backend\api\src\modules\server.common` and into `admin\website-angular\src\modules\server.common` and folder content `shared/core-angular` into `C:\Coding\Ever\ever\admin\website-angular\src\modules\client.common.angular2`. This way you will "bypass" issues with symlinks and should be able to run both Admin UI and Server in my opinion...

For other projects in our platform, you will need to do the same manual copy.

Let me know if that helps!

**Comment by healer2030** [comment]
@evereq I tried copying the folders manually but I wasn't able get into the folder so I deleted the symlinks and then using the MKLink tool in the Windows Command Prompt in Administrator mode, I recreated the symlinks with the following commands

- `mklink /D C:\Coding\Ever\ever\backend\api\src\modules\server.common C:\Coding\Ever\ever\shared\core`

- `mklink /D C:\Coding\Ever\ever\admin\website-angular\src\modules\server.common C:\Coding\Ever\ever\shared\core`

- `mklink /D C:\Coding\Ever\ever\admin\website-angular\src\modules\client.common.angular2 C:\Coding\Ever\ever\shared\core-angular`

it should look something like this when done:
![Capture](https://user-images.githubusercontent.com/23042845/63124744-fbebe680-bf79-11e9-8d7d-f2186fef9e2e.PNG)

**Comment by evereq** [comment]
@healer2030 oh thanks for the great workaround! I think we can even create some *.cmd / *.bat file which will execute such commands for all projects in our platform on Windows and can be used temporarily before we moved out from symlinks completely! Very cool, thanks!

**Comment by evereq** [comment]
@AlishMekliov931 can you please write such recreate_symlinks.bat file and put it into the root folder of the repo? Inside that file, just remove existed symlinks for every project like this `cmd /c rmdir .\Target` (it's required to run via `cmd`, otherwise it will remove whole target folder with `rmdir` command). Next, create every required symlink using `mklink` like suggested by @healer2030.

**Comment by evereq** [comment]
So, this is a full list of commands useful to "recreate" symlinks (from Console running as Administrator on Windows):
```
cmd /c rmdir .\admin\website-angular\src\modules\server.common
cmd /c rmdir .\admin\website-angular\src\modules\client.common.angular2
cmd /c rmdir .\backend\api\src\modules\server.common
cmd /c rmdir .\carrier\mobile-ionic\src\modules\server.common
cmd /c rmdir .\carrier\mobile-ionic\src\modules\client.common.angular2
cmd /c rmdir .\merchant\tablet-ionic\src\modules\server.common
cmd /c rmdir .\merchant\tablet-ionic\src\modules\client.common.angular2
cmd /c rmdir .\shop\mobile-ionic\src\modules\server.common
cmd /c rmdir .\shop\mobile-ionic\src\modules\client.common.angular2
cmd /c rmdir .\shop\website-angular\src\modules\server.common
cmd /c rmdir .\shop\website-angular\src\modules\client.common.angular2
mklink /D admin\website-angular\src\modules\server.common shared\core
mklink /D admin\website-angular\src\modules\client.common.angular2 shared\core-angular
mklink /D backend\api\src\modules\server.common shared\core
mklink /D carrier\mobile-ionic\src\modules\server.common shared\core
mklink /D carrier\mobile-ionic\src\modules\client.common.angular2 shared\core-angular
mklink /D merchant\tablet-ionic\src\modules\server.common shared\core
mklink /D merchant\tablet-ionic\src\modules\client.common.angular2 shared\core-angular
mklink /D shop\mobile-ionic\src\modules\server.common shared\core
mklink /D shop\mobile-ionic\src\modules\client.common.angular2 shared\core-angular
mklink /D shop\website-angular\src\modules\server.common shared\core
mklink /D shop\website-angular\src\modules\client.common.angular2 shared\core-angular
```

However, in all PATHs above used in `mklink`, it looks like full PATH is required, e.g. like 
`mklink /D C:\Coding\Ever\ever\backend\api\src\modules\server.common C:\Coding\Ever\ever\shared\core`, otherwise symlinks created the wrong way and did not work...
