### ISSUE TITLE
Add loading indicator in the Ban/Unban

### ISSUE THREAD

**Issue by BlagovestGerov** [ever-co/ever#556]
Add loading indicator while the request to Ban/Unban user is in process or/and add message notification (angular toaster notification). We have implemented such in other places in the admin app.

**Comment by evereq** [comment]
@AdemHodzic some more improvements to be done:
a) Make button Ban/Unban disabled, during the request process. 
b) In the Toaster notification add the user name. For example “Annabel O’Keefe is banned!“.

![LoadingIndImpr](https://user-images.githubusercontent.com/118497/58819137-365f0c00-8638-11e9-9aed-a3a5cace1882.png)
