### ISSUE TITLE
Add fake data with Ban users

### ISSUE THREAD

**Issue by BlagovestGerov** [ever-co/ever#559]
Basically, randomly make few customers to be banned customers during fake data generation

**Comment by evereq** [comment]
@AdemHodzic It looks like no fake Banned users are generated. 

Reported by @BlagovestGerov: "I dropped the Database several times but after generating again fake data I didn’t find fake generated banned users."

**Comment by AdemHodzic** [comment]
Hmm, well this is quite random so I would guess he was just unlucky lol
But seriously, I didn't change any previous functionality. I just introduced a new field.
Did it persist to the database before?

**Comment by evereq** [comment]
@AdemHodzic I think the issue here is that random values you generate somehow always get constant value (e.g. false) and so we don't really see any fake generated banned users :) You need to run it locally and see if some of the fake records get banned = true...

**Comment by evereq** [comment]
@AdemHodzic so as we discover it looks like for at least `generate100users` we see around 4 banned users from 100... But seems when we generate all fake data we don't see such users... Could be we have other methods which generate random users and we need to add "random" banned there too :)

**Comment by AdemHodzic** [comment]
I just find out we are using a different method in generateAll. In this case, we are using a graphql mutation and in other, we are using plain HTTP request
