### ISSUE TITLE
ArcGIS vs Google Geocoding

### ISSUE THREAD

**Issue by evereq** [ever-co/ever#642]
In the mobile app, we are using ArcGIS (http://www.arcgis.com) for geocoding and for admin app we are using google geocoder. However, ArcGIS is not a free or very popular service, we need to check the reason why we used it and see if we can use Google geocoder instead (and have ArcGIS as an optional extension which is possible to enable/disable with .env file configuration)

**Comment by AlishMekliov931** [comment]
@evereq  This ArcGIS is used from the beginning, even in the older version on the app, so I don't know why. I'll do it like if ARCGIS_CLIENT_ID and ARCGIS_CLIENT_SECRET are not provided on the server .env file, then to use Google geocoder. 
![chrome_IYkrHVEw6H](https://user-images.githubusercontent.com/22296670/61885753-11d03380-af07-11e9-9903-5812ea5e783c.png)

**Comment by AlishMekliov931** [comment]
Now if ARCGIS_CLIENT_ID and ARCGIS_CLIENT_SECRET are not provided on the server .env file, customer app will just get location from Google geocoder.
