### ISSUE TITLE
 Cannot find module '@modules/server.common/utils'

### ISSUE THREAD

**Issue by fkorteby** [ever-co/ever#786]
Hi,

First i want to thank you for this great job.

Second while installing i got some issue with some modules under **@modules/server.common/**

I checked in my modules folder and i am not able to /server.common/ folder.

Any help ? Thank you in advance.

Bellow the trace after trying to start the backend :

yarn run v1.17.3
$ yarn --cwd ./backend/api start
$ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn tsc && node build/main.js
$ "E:\Mine\Food Ordering\ever\backend\api\node_modules\.bin\tsc"
src/graphql/geo-locations/merchants/geo-location-merchants.resolver.ts:5:19 - error TS2307: Cannot find module '@modules/server.common/utils'.

5 import Utils from '@modules/server.common/utils';
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/graphql/warehouses/warehouse.resolver.ts:22:19 - error TS2307: Cannot find module '@modules/server.common/utils'.
22 import Utils from '@modules/server.common/utils';
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/modules/server.common/@pyro/db/db-object.ts:6:24 - error TS2307: Cannot find module '../../utils'.

6 import { toDate } from '../../utils';
                         ~~~~~~~~~~~~~

src/services/carriers/CarriersOrdersService.ts:20:29 - error TS2307: Cannot find module '@modules/server.common/utils'.

20 import { getDistance } from '@modules/server.common/utils';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/services/geo-locations/GeoLocationsProductsService.ts:8:19 - error TS2307: Cannot find module '@modules/server.common/utils'.

8 import Utils from '@modules/server.common/utils';
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/services/geo-locations/GeoLocationsWarehousesService.ts:4:19 - error TS2307: Cannot find module '@modules/server.common/utils'.

4 import Utils from '@modules/server.common/utils';
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/services/invites/InvitesRequestsService.ts:15:32 - error TS2307: Cannot find module '@modules/server.common/notifications'.

15 import * as notifications from '@modules/server.common/notifications';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/services/invites/InvitesService.ts:3:19 - error TS2307: Cannot find module '@modules/server.common/utils'.

3 import Utils from '@modules/server.common/utils';
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/services/services.app.ts:29:31 - error TS2307: Cannot find module '@modules/server.common/utils'.

29 import { getDummyImage } from '@modules/server.common/utils';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/test/integration/GeoLocationWarehouses.spec.ts:18:37 - error TS2307: Cannot find module '@modules/server.common/utils'.

18 import { getPlaceholditImgix } from '@modules/server.common/utils';
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 10 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by evereq** [comment]
Hey @fkorteby thanks! :)

Regarding your issue, I think you cloned repo without the support of symlinks.
So you need to clone again, best from console running "as administrator" with the following command: 
```
git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git
```

See more info at https://github.com/ever-co/ever#clone-repo

**Comment by fkorteby** [comment]
Yes i did the exact command to clone the repo

**Comment by fkorteby** [comment]
to make it simple, is there any way to download the module manually ? i cannot find it any where i think its not npm module correct ?

**Comment by evereq** [comment]
@fkorteby are you sure you run the same command from the console with administrator priveledges?

Can you please try again to clone the repo and attach here output from your console (as well as the command you run to clone repo)? It is possible you got many warning errors during the cloning process.
Also, you can try to navigate from windows explorer to folder `backend/api/src/modules` and see if you have there subfolder `server.common` and try to browse that folder. If you can't browse it proves symlinks do not work for you...

The logic is simple: symlinks make files like `backend/api /src/modules/server.common/@pyro/db/db-object.ts` to be loaded from the other directory: `shared/core/@pyro/db/db-object.ts`. 
You do not need to copy anything manually, you only need to make symlinks working.

See for example file it tries to load here: https://github.com/ever-co/ever/blob/develop/shared/core/%40pyro/db/db-object.ts

**Comment by fkorteby** [comment]
OK i repeated the process it seems everything is going well :

> -------------------------------------------------------------------------------------------------
> E:\Mine\Food Ordering>git clone -c core.symlinks=true --recursive https://github.com/ever-co/ever.git
> Cloning into 'ever'...
> remote: Enumerating objects: 396, done.
> remote: Counting objects: 100% (396/396), done.
> remote: Compressing objects: 100% (323/323), done.
> remote: Total 12246 (delta 253), reused 71 (delta 32), pack-reused 11850Receiving objects:  99% (12124/12246), 14.51 MiB | 1.05 MiB/s
> Receiving objects: 100% (12246/12246), 17.22 MiB | 1001.00 KiB/s, done.
> Resolving deltas: 100% (7435/7435), done.
> Checking out files: 100% (2770/2770), done.
> -------------------------------------------------------------------------------------------------

After i checked the directory **ever\backend\api\src\modules** i can find like shortcut there so it looks like symlinks is working fine for me.

I tried to open the shortcut server.common with atom so i am able to all files including of this package :

![image](https://user-images.githubusercontent.com/34208201/62429037-0d2f2a80-b712-11e9-86e1-96b25f6f6acf.png)

After i did **yarn bootstrap** below the result :

> E:\Mine\Food Ordering\ever>yarn bootstrap
> yarn run v1.17.3
> $ yarn install && yarn lerna bootstrap
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> info fsevents@1.2.4: The platform "win32" is incompatible with this module.
> info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
> [4/5] Linking dependencies...
> warning " > @angular/core@7.2.14" has unmet peer dependency "zone.js@~0.8.26".
> warning " > @angular/platform-browser@7.2.14" has unmet peer dependency "@angular/common@7.2.14".
> warning " > @angular/platform-browser-dynamic@7.2.14" has unmet peer dependency "@angular/common@7.2.14".
> warning " > @angular/platform-browser-dynamic@7.2.14" has unmet peer dependency "@angular/compiler@7.2.14".
> warning " > @nestjs/typeorm@6.1.1" has unmet peer dependency "@nestjs/common@^6.0.0".
> warning " > @nestjs/typeorm@6.1.1" has unmet peer dependency "@nestjs/core@^6.0.0".
> warning " > @nestjs/typeorm@6.1.1" has unmet peer dependency "reflect-metadata@0.1.12".
> warning " > @ngx-translate/http-loader@4.0.0" has unmet peer dependency "@angular/common@>=7.0.0".
> warning " > angular2-logger@0.7.0" has unmet peer dependency "@angular/common@^4.0.2 || ^5.0.0".
> warning " > angular2-logger@0.7.0" has unmet peer dependency "@angular/compiler@^4.0.2 || ^5.0.0".
> warning " > angular2-logger@0.7.0" has incorrect peer dependency "@angular/core@^4.0.2 || ^5.0.0".
> warning " > angular2-logger@0.7.0" has incorrect peer dependency "@angular/platform-browser@^4.0.2 || ^5.0.0".
> warning " > angular2-logger@0.7.0" has incorrect peer dependency "@angular/platform-browser-dynamic@^4.0.2 || ^5.0.0".
> warning " > codelyzer@5.0.1" has unmet peer dependency "@angular/compiler@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0".
> [5/5] Building fresh packages...
> $ yarn run snyk-protect
> $ snyk protect
> Successfully applied Snyk patches
> 
> $ "E:\Mine\Food Ordering\ever\node_modules\.bin\lerna" bootstrap
> lerna notice cli v3.13.4
> lerna info Bootstrapping 6 packages
> lerna info Installing external dependencies
> lerna info Symlinking packages and binaries
> lerna info lifecycle ever-shop-web@0.2.0~postinstall: ever-shop-web@0.2.0
> 
> > ever-shop-web@0.2.0 postinstall E:\Mine\Food Ordering\ever\shop\website-angular
> > cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn run config:dev && yarn run webdriver:update
> 
> $ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn run config -- --environment=dev
> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
> $ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn ts-node ./scripts/configure.ts --environment=dev
> $ "E:\Mine\Food Ordering\ever\shop\website-angular\node_modules\.bin\ts-node" ./scripts/configure.ts --environment=dev
> WARNING: No Google Maps API Key defined in the .env. Google Maps may not be visible!
> Generated Second Empty Angular environment file: environment.ts
> Generated Angular environment file: environment.ts
> $ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn run config:dev && node --max_old_space_size=4096 ./node_modules/protractor/bin/webdriver-manager update
> $ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn run config -- --environment=dev
> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
> $ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn ts-node ./scripts/configure.ts --environment=dev
> $ "E:\Mine\Food Ordering\ever\shop\website-angular\node_modules\.bin\ts-node" ./scripts/configure.ts --environment=dev
> WARNING: No Google Maps API Key defined in the .env. Google Maps may not be visible!
> Generated Second Empty Angular environment file: environment.ts
> Generated Angular environment file: environment.ts
> [00:25:38] I/file_manager - creating folder E:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium
> [00:25:38] I/config_source - curl -oE:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
> [00:25:38] I/config_source - curl -oE:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
> [00:25:38] I/config_source - curl -oE:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
> [00:25:47] I/downloader - curl -oE:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium/chromedriver_2.46.zip https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip
> [00:25:48] I/downloader - curl -oE:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium/selenium-server-standalone-4.0.0-alpha-2.zip.jar https://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-2.zip
> [00:25:49] I/downloader - curl -oE:\Mine\Food Ordering\ever\shop\website-angular\node_modules\webdriver-manager\selenium/geckodriver-v0.24.0.zip https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-win64.zip
> [00:26:09] I/update - geckodriver: unzipping geckodriver-v0.24.0.zip
> [00:26:33] I/update - chromedriver: unzipping chromedriver_2.46.zip
> lerna info lifecycle ever-api@0.2.0~prepublish: ever-api@0.2.0
> 
> > ever-api@0.2.0 prepublish E:\Mine\Food Ordering\ever\backend\api
> > yarn run snyk-protect
> 
> $ yarn snyk protect
> $ "E:\Mine\Food Ordering\ever\backend\api\node_modules\.bin\snyk" protect
> Successfully applied Snyk patches
> 
> lerna success Bootstrapped 6 packages
> Done in 2602.45s.

After when i run **yarn run:server** i got the same issue any idea ? :

> E:\Mine\Food Ordering\ever>yarn run:server
> yarn run v1.17.3
> $ yarn --cwd ./backend/api start
> $ cross-env NODE_ENV=development NODE_OPTIONS=--max_old_space_size=4096 yarn tsc && node build/main.js
> $ "E:\Mine\Food Ordering\ever\backend\api\node_modules\.bin\tsc"
> src/graphql/geo-locations/merchants/geo-location-merchants.resolver.ts:5:19 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 5 import Utils from '@modules/server.common/utils';
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/graphql/warehouses/warehouse.resolver.ts:22:19 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 22 import Utils from '@modules/server.common/utils';
>                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/modules/server.common/@pyro/db/db-object.ts:6:24 - error TS2307: Cannot find module '../../utils'.
> 
> 6 import { toDate } from '../../utils';
>                          ~~~~~~~~~~~~~
> 
> src/services/carriers/CarriersOrdersService.ts:20:29 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 20 import { getDistance } from '@modules/server.common/utils';
>                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/services/geo-locations/GeoLocationsProductsService.ts:8:19 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 8 import Utils from '@modules/server.common/utils';
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/services/geo-locations/GeoLocationsWarehousesService.ts:4:19 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 4 import Utils from '@modules/server.common/utils';
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/services/invites/InvitesRequestsService.ts:15:32 - error TS2307: Cannot find module '@modules/server.common/notifications'.
> 
> 15 import * as notifications from '@modules/server.common/notifications';
>                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/services/invites/InvitesService.ts:3:19 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 3 import Utils from '@modules/server.common/utils';
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/services/services.app.ts:29:31 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 29 import { getDummyImage } from '@modules/server.common/utils';
>                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> src/test/integration/GeoLocationWarehouses.spec.ts:18:37 - error TS2307: Cannot find module '@modules/server.common/utils'.
> 
> 18 import { getPlaceholditImgix } from '@modules/server.common/utils';
>                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Found 10 errors.
> 
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by evereq** [comment]
@fkorteby today our developer @AlishMekliov931 tried to reproduce your issues but without any success... He tried to follow steps you did on two separate PCs, both with Windows 10 and every time all was fine (he cloned `develop` branch, which is set as default branch)... 

It still feels like there are some issues with symlinks on your PC, but we don't know what exactly (because from errors we clearly see an attempt to load TS module from filesystem failing)... 

On the positive note: we are working to migrate into full "packages" structure (supported by Lerna), so we will not need symlinks in the future. However, we can't tell yet how long it might take to make that new config working. Before that, I suggest to try on some other PC / config if you can.

**Comment by evereq** [comment]
@fkorteby also I notice your folder is "Food Ordering", it sounds crazy but sometimes spaces in the folder names can cause issues... We usually using folders like `C:/Coding/ever` on Windows to avoid such possible issues (it could be no issue at all of course... still it's the only thing which I can spot from logs)

**Comment by fkorteby** [comment]
Thank you guys for your help.

Anyway i was able to do a work around by copying required packages manually to each project.
