### ISSUE TITLE
Is it possible to add product search button in Ever Mobile Shop App?

### ISSUE THREAD

**Issue by SaddamDeveloper** [ever-co/ever#806]
The whole package is outstanding. Seriously, I need one product search button btw I can search Merchant Name. But I need more specific search for product.

**Comment by evereq** [comment]
@SaddamDeveloper, thanks for feedback and suggestion. 
We have a separate repo to track feature requests, so I added your request here: https://github.com/ever-co/feature-requests/issues/15.
We will prioritize it and let you know when it's implemented.

Thanks again for trying Ever Platform!

**Comment by evereq** [comment]
@AlishMekliov931 so essentially we need to add a tiny search icon to the header of app, align it to the right so it always displayed to the right from takeout/delivery switch) and if customer click on it, show some one-line input for product name (in place of current "Products" title and switch for takeout/delivery) which filters available products according to the entered text (not sure yet should it filter on the server-side or on the client-side, needs to research flow). 

For icons see: https://fontawesome.com/icons/search?style=solid or ionic `<ion-icon name="search"></ion-icon>`

Note: it should show both stores (restaurants) with name which starts from entered text and also products, which names or short description starts from entered text. Autocomplete not needed for now. Inside the input, you can put placeholder "Product or a shop name"
