### ISSUE TITLE
yarn run:server failure

### ISSUE THREAD

**Issue by saurabh1223** [ever-co/ever#810]
I am facing issue in yarn run:server

Logs :- 

Error while  src/@pyro/db-server/db-service.ts:12:26 - error TS2307: Cannot find module '@pyro/db'.  12 import { DBObject } from '@pyro/db';

**Comment by saurabh1223** [comment]
[Ever_errors.txt](https://github.com/ever-co/ever/files/3522049/Ever_errors.txt)

**Comment by saurabh1223** [comment]
Please find the errors attached.

**Comment by evereq** [comment]
@saurabh1223 I think you experience issues with 'symlinks', we talked about it in other tickets, see https://github.com/ever-co/ever/issues?q=is%3Aissue+symlink+is%3Aclosed
