### ISSUE TITLE
Admin UI : Stores : Create : a Maps JavaScriptAPI Error appears when creating a store

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#978]
Maps JavaScriptAPI Error appears when creating a store

![image-20200116-205719](https://user-images.githubusercontent.com/59708947/72925703-e9988480-3d31-11ea-88e7-ed2cbd1e78ab.png)

https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=places_js&utm_medium=degraded&utm_campaign=keyless#api-key-and-billing-errors

**Comment by AlishMekliov931** [comment]
@morggansoft This error appears because of no value set on setting "GOOGLE_MAPS_API_KEY". 
To fix it add such setting in .env file (GOOGLE_MAPS_API_KEY={your google maps API key}) and rebuild the app.

**Comment by morggansoft** [comment]
We cheked and the .env file was already set with the variable. Anyway we made a rebuild just in case with the .env file set, and the error continues:

![image](https://user-images.githubusercontent.com/59708947/73858297-eebc0000-4816-11ea-8766-abecdde77408.png)

**Comment by AlishMekliov931** [comment]
@morggansoft The issue is produced by Google API, so I can't fix it. You can see in the develop console 
![chrome_icLXlW2E2B](https://user-images.githubusercontent.com/22296670/75894705-4e6cf180-5e3d-11ea-97b8-9be1ac877bec.png)
CC: @evereq

**Comment by morggansoft** [comment]
Solved by enabling MAPS Geocoding API in Google Cloud Platform.
