### ISSUE TITLE
Admin UI : Stores : Select Store : Products : Edit Product : back button goes somewhere else

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#979]
In this section if you press the go back button it will take yoo to the general products administration instead of the section in Stores where the user was navigating before.

![image-20200117-210102](https://user-images.githubusercontent.com/59708947/72926103-9b37b580-3d32-11ea-8a01-0cc5b3d6c184.png)

![image-20200117-210154](https://user-images.githubusercontent.com/59708947/72926118-a0950000-3d32-11ea-9b3a-a0b8d43b43e8.png)

**Comment by YavorGrancharov** [comment]
I tested it and I think it works fine! Provided a video for preview.

https://www.loom.com/share/9443fd40215a4df6b0e1636c0f1437db
