### ISSUE TITLE
Admin UI : Stores : manage stores : when changing store password

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#981]
You cannot press the save button twice since the password fields are sticked with the typed password, so it leaves a message that password is incorrect the second time you press save.

After saving the fields should be emptied.

![image-20200116-215802](https://user-images.githubusercontent.com/59708947/72927815-a3452480-3d35-11ea-8eb7-5ca689829752.png)

**Comment by YavorGrancharov** [comment]
Fixed
https://www.loom.com/share/a915842018ed4bf08e50a0bde87f0473
