### ISSUE TITLE
Admin UI : Stores : Create : during store creation the autofill does not work

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#982]
Not sure if this is bug. In the videos showing store creation there was an autofill, maybe this is not a feature but a client navigator configuration, but in case there should be working an autofill it is not working.

![image-20200116-204447](https://user-images.githubusercontent.com/59708947/72928489-d4722480-3d36-11ea-9def-76c8d0c10ebd.png)

**Comment by evereq** [comment]
@AlishMekliov931 could it be because Google Maps API key is wrong for example? I.e. that feature for location "autocomplete" probably implemented using Google Maps API or? Please check and let us know

**Comment by AlishMekliov931** [comment]
@evereq , @morggansoft Yes, this is because of no value or wrong one is set on setting "GOOGLE_MAPS_API_KEY".
To fix it add such setting in .env file (GOOGLE_MAPS_API_KEY={your google maps API key}) and rebuild the app.

**Comment by morggansoft** [comment]
The .env file was set like this. Autofill still does not work.

![image](https://user-images.githubusercontent.com/59708947/73860143-e0231800-4819-11ea-9c0d-83075d20de8e.png)

**Comment by morggansoft** [comment]
Solved enabling MAPS Geocoding API in Google Cloud Platform.
