### ISSUE TITLE
Admin UI : Stores : after you click on "show on map" you cannot go back to the Store list, only by pressing the Store menu again

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#983]
![image-20200116-202337](https://user-images.githubusercontent.com/59708947/72931274-5153cd00-3d3c-11ea-9220-510520b816b8.png)

**Comment by YavorGrancharov** [comment]
Fixed
https://www.loom.com/share/17a4354249cc4f189d27be0f2e669326
