### ISSUE TITLE
Carrier App - Deliveries History

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#986]
Deliveries History does not work well. 

Show messaging: Cannot GET / deliveries when clicked on Delivery History option

**Comment by AlishMekliov931** [comment]
@morggansoft The bug is fixed, and code pushed in develop branch. You can pull the last changes and after rebuild the apps, you will see the fixes.

**Comment by morggansoft** [comment]
Solved. This feature is working Ok.
