### ISSUE TITLE
API warning with Apollo Engine Key

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#988]
![image](https://user-images.githubusercontent.com/59708947/73073613-74928f80-3e96-11ea-9ee0-e904be741857.png)

In the logs of all modules appears this error.

Perhaps it is related to #978 Admin UI : Stores : Create : a Maps JavaScriptAPI Error appears when creating a store

**Comment by morggansoft** [comment]
New finding: they are most likely produced by this conf:

# Apollo Engine Key (optional, see https://www.apollographql.com/docs/platform/schema-registry)
ENGINE_API_KEY=service:XXXXX:XXXXXXXX

**Comment by evereq** [comment]
OK, yes, so it's optional setting and not really important one, closing this issue :)
