### ISSUE TITLE
Merchant App: Customer Data

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#989]
Customer data is not displayed when creating new  manual order from the Merchant App.

**Comment by morggansoft** [comment]
![Captura de Pantalla 2020-01-24 a la(s) 23 24 33](https://user-images.githubusercontent.com/59708947/73115157-4f873680-3f01-11ea-86f9-9d15b96c7af0.png)

**Comment by AlishMekliov931** [comment]
@morggansoft The base functionality required a customer to have a valid address whare will be sent orders, all other fields like name, email, phone etc. are optional. So in your case, the customers which are shown on the current page just don't have such values.

**Comment by morggansoft** [comment]
The answer is correct. The data in the database is incomplete, and that is why the error occurs. Perhaps requesting this information as mandatory could be a new Feature for our version.
