### ISSUE TITLE
Feature: Admin UI -> Stores -> Select Store -> Products -> Select Product - there is no back button

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#995]
When entering a product to see its description there's no back button to go right back to the previous screen.

![image](https://user-images.githubusercontent.com/59708947/73877960-6c443800-4838-11ea-8ca8-8a7be5639a22.png)

![image](https://user-images.githubusercontent.com/59708947/73877995-7f570800-4838-11ea-86d7-bd8158b26bc2.png)

**Comment by evereq** [comment]
@YavorGrancharov just check how it's done on other similar pages and do here :)

**Comment by YavorGrancharov** [comment]
Ok!

На нд, 1.03.2020 г., 13:47 Ruslan Konviser <notifications@github.com>
написа:

**Comment by YavorGrancharov** [comment]
Fixed
![MPqOm3tAIL](https://user-images.githubusercontent.com/28997304/84568960-ae076100-ad8b-11ea-8399-d897d000ff2c.png)
