### ISSUE TITLE
Bug: Mobile Shop -> Sign up by address not working

### ISSUE THREAD

**Issue by morggansoft** [ever-co/ever#996]
Mobile shop sign up by address not working.

![image](https://user-images.githubusercontent.com/59708947/73881395-014a2f80-483f-11ea-921a-4623583ce257.png)

**Comment by morggansoft** [comment]
With google and facebook not working either...

![image](https://user-images.githubusercontent.com/59708947/73881695-8fbeb100-483f-11ea-8d29-624d7d395c0a.png)

**Comment by evereq** [comment]
@AlishMekliov931 please check that, I am pretty sure that should be working (except FB / Google, think we did not finish implementing them @morggansoft).

Also @morggansoft I would suggest disabling Invite system unless you need it (i doubt), @AlishMekliov931 thought it should be disabled by default in the mobile shop, no? In any case, please describe here how to disable it

**Comment by evereq** [comment]
@AlishMekliov931 think you fixed this recently, right? Can we close?

**Comment by morggansoft** [comment]
Actually we deactivated sign-in by address, so we don't truly know if it's still there or not. What I can tell you is that we won't be able to test it, so close if if you wish.

Nevertheless,  I suspect it is related to issues #978 and #1014. If I am right on this suspicion by fixing them this one should get fixed also.

**Comment by AlishMekliov931** [comment]
@morggansoft You can't deactivated sign-in by address. Can you try again after #978 and #1014 are fixed.

**Comment by morggansoft** [comment]
Thanks @AlishMekliov931, I forgot to close this issue yesterday. Actually we specifically made a rebuild with SETTINGS_REGISTRATIONS_REQUIRED_ON_START=true to test this after enabling MAPS Geolocation API. The issue is solved.
